import type { DesignSystemPreset } from "@sdd/contracts";

/**
 * Curated starting points. Style families are adapted from the generic
 * packages of nexu-io/open-design (Apache-2.0) — no brand-named systems —
 * with contrast fixed to WCAG AA and a dark mode added to each.
 * tests/design-system.unit.test.ts keeps every palette above the minimums.
 */

const SYSTEM = 'system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif';
const SANS = `"Inter", ${SYSTEM}`;
const GEOMETRIC = `"Manrope", "Avenir Next", ${SYSTEM}`;
const HUMANIST = `"Source Sans 3", "Segoe UI", "Helvetica Neue", ${SYSTEM}`;
const ROUNDED = `"Nunito", "Segoe UI", ${SYSTEM}`;
const ROBOTO = `"Roboto", ${SYSTEM}`;
const GROTESK = `"Space Grotesk", "Helvetica Neue", Arial, sans-serif`;
const SERIF_DISPLAY = '"Fraunces", "Iowan Old Style", Georgia, "Times New Roman", serif';
const SERIF_BODY = '"Newsreader", "Iowan Old Style", Georgia, "Times New Roman", serif';
const MONO = '"JetBrains Mono", ui-monospace, "SF Mono", Menlo, Consolas, monospace';

export const DESIGN_SYSTEM_PRESETS: DesignSystemPreset[] = [
  {
    id: "minimal",
    name: "Minimal",
    summary: "White space, black type, hairline borders and one quiet accent. Lets the content lead.",
    tags: ["Neutral", "SaaS", "Docs"],
    light: { bg: "#ffffff", surface: "#ffffff", surface2: "#f4f4f5", fg: "#18181b", fgMuted: "#5f5f67", border: "#e4e4e7", borderStrong: "#8b8b93", accent: "#18181b", accentFg: "#ffffff", success: "#15803d", warn: "#b45309", danger: "#b91c1c", info: "#1d4ed8" },
    dark: { bg: "#09090b", surface: "#131316", surface2: "#1d1d21", fg: "#fafafa", fgMuted: "#a1a1aa", border: "#2a2a30", borderStrong: "#6b6b75", accent: "#fafafa", accentFg: "#09090b", success: "#4ade80", warn: "#fbbf24", danger: "#f87171", info: "#60a5fa" },
    fonts: { display: SANS, body: SANS, mono: MONO },
    radius: 6,
    density: "comfortable",
    depth: "hairline",
    border_width: 1,
    guidance: [
      "## Character",
      "Calm, precise and content-first. Hierarchy comes from size, weight and space — not colour.",
      "## Colour",
      "Almost monochrome. The accent is the ink colour itself; status colours appear only for status.",
      "## Shape and depth",
      "Hairline borders separate regions; no shadows except on overlays. Corners stay small and consistent.",
      "## Do",
      "- Use generous white space between groups and tight spacing inside them.",
      "- Keep one primary button per view.",
      "## Avoid",
      "- Decorative colour, gradients and heavy shadows.",
      "- More than two type weights on one screen.",
    ].join("\n"),
  },
  {
    id: "modern-saas",
    name: "Modern SaaS",
    summary: "Cool greys, a confident blue and soft elevation. The familiar, trustworthy product look.",
    tags: ["SaaS", "Dashboard", "B2B"],
    light: { bg: "#f8fafc", surface: "#ffffff", surface2: "#f1f5f9", fg: "#0f172a", fgMuted: "#526077", border: "#e2e8f0", borderStrong: "#8391a7", accent: "#2563eb", accentFg: "#ffffff", success: "#15803d", warn: "#b45309", danger: "#b91c1c", info: "#0369a1" },
    dark: { bg: "#0b1120", surface: "#111a2e", surface2: "#1a2540", fg: "#e2e8f0", fgMuted: "#94a3b8", border: "#243049", borderStrong: "#5b6b88", accent: "#60a5fa", accentFg: "#0b1120", success: "#4ade80", warn: "#fbbf24", danger: "#f87171", info: "#38bdf8" },
    fonts: { display: SANS, body: SANS, mono: MONO },
    radius: 8,
    density: "comfortable",
    depth: "soft",
    border_width: 1,
    guidance: [
      "## Character",
      "Clear, dependable and efficient. Feels like a well-made tool rather than a brand statement.",
      "## Colour",
      "Blue marks actions, links, focus and the current selection. Everything else is slate grey.",
      "## Shape and depth",
      "Cards sit on a tinted page with a soft shadow and a light border. Medium radius throughout.",
      "## Do",
      "- Group related settings in cards with a clear title and one-line description.",
      "- Use tables with a tinted header row for lists of records.",
      "## Avoid",
      "- Blue for decoration or large filled areas.",
      "- Mixing rounded and sharp corners.",
    ].join("\n"),
  },
  {
    id: "editorial",
    name: "Editorial",
    summary: "Warm paper, ink-dark text and a serif display face. Reads like a well-set publication.",
    tags: ["Content", "Blog", "Publishing"],
    light: { bg: "#fbf8f3", surface: "#fffdf9", surface2: "#f3ede3", fg: "#1c1917", fgMuted: "#5c5550", border: "#e7dfd3", borderStrong: "#8f8579", accent: "#9f1239", accentFg: "#ffffff", success: "#166534", warn: "#9a3412", danger: "#b91c1c", info: "#1e40af" },
    dark: { bg: "#171412", surface: "#1f1b18", surface2: "#2a2521", fg: "#f3ede3", fgMuted: "#b3a99c", border: "#3a332d", borderStrong: "#7a6f64", accent: "#fb7185", accentFg: "#171412", success: "#86efac", warn: "#fdba74", danger: "#fca5a5", info: "#93c5fd" },
    fonts: { display: SERIF_DISPLAY, body: SERIF_BODY, mono: MONO },
    radius: 2,
    density: "spacious",
    depth: "hairline",
    border_width: 1,
    guidance: [
      "## Character",
      "Literary and unhurried. Typography does the work: large serif headlines, comfortable reading measure.",
      "## Colour",
      "Warm paper and ink. The deep red accent is used sparingly for links and the single primary action.",
      "## Typography",
      "Serif for headlines and long text; keep lines to 60–75 characters. Use small caps or italics, not bold, for emphasis.",
      "## Do",
      "- Lead each page with a strong headline and a one-paragraph standfirst.",
      "- Use rules (thin lines) to separate sections.",
      "## Avoid",
      "- Card grids and heavy UI chrome.",
      "- Sans-serif display text.",
    ].join("\n"),
  },
  {
    id: "brutalist",
    name: "Brutalist",
    summary: "Thick black borders, hard offset shadows, raw type and a loud yellow highlight.",
    tags: ["Bold", "Portfolio", "Indie"],
    light: { bg: "#fffdf2", surface: "#ffffff", surface2: "#ffe45c", fg: "#000000", fgMuted: "#3d3d3d", border: "#000000", borderStrong: "#000000", accent: "#000000", accentFg: "#ffe45c", success: "#0f7a33", warn: "#9a5b00", danger: "#c1121f", info: "#1d3fcf" },
    dark: { bg: "#111111", surface: "#1b1b1b", surface2: "#3a3200", fg: "#fffdf2", fgMuted: "#cfcfcf", border: "#fffdf2", borderStrong: "#fffdf2", accent: "#ffe45c", accentFg: "#000000", success: "#5ee08a", warn: "#ffc24d", danger: "#ff7a7a", info: "#8fb0ff" },
    fonts: { display: GROTESK, body: GROTESK, mono: MONO },
    radius: 0,
    density: "comfortable",
    depth: "hard",
    border_width: 3,
    guidance: [
      "## Character",
      "Direct, confident and a little rough. Structure is visible on purpose.",
      "## Colour",
      "Black and off-white, with the yellow highlight as the only colour — for fills behind key items, never for text on white.",
      "## Shape and depth",
      "Square corners, 3px black borders and a hard offset shadow (no blur) on cards and buttons.",
      "## Do",
      "- Use uppercase labels sparingly for section markers.",
      "- Let blocks touch the grid edges; alignment matters more than decoration.",
      "## Avoid",
      "- Soft shadows, gradients and rounded corners.",
      "- Grey-on-grey text.",
    ].join("\n"),
  },
  {
    id: "playful",
    name: "Playful",
    summary: "Rounded shapes, a bright violet and friendly type. Approachable without being childish.",
    tags: ["Consumer", "Education", "Community"],
    light: { bg: "#fbfaff", surface: "#ffffff", surface2: "#f1edff", fg: "#1e1537", fgMuted: "#5d5474", border: "#e4dcfb", borderStrong: "#8e82b3", accent: "#6d28d9", accentFg: "#ffffff", success: "#15803d", warn: "#b45309", danger: "#be123c", info: "#0369a1" },
    dark: { bg: "#130f22", surface: "#1c1731", surface2: "#282042", fg: "#f1edff", fgMuted: "#b1a8cf", border: "#342b54", borderStrong: "#7466a3", accent: "#b69cff", accentFg: "#130f22", success: "#4ade80", warn: "#fbbf24", danger: "#fb7185", info: "#7dd3fc" },
    fonts: { display: ROUNDED, body: ROUNDED, mono: MONO },
    radius: 14,
    density: "comfortable",
    depth: "soft",
    border_width: 2,
    guidance: [
      "## Character",
      "Warm, encouraging and energetic. Small moments of delight, never at the cost of clarity.",
      "## Colour",
      "Violet for actions and progress; tinted lilac surfaces group content. Status colours stay standard.",
      "## Shape and depth",
      "Generous rounding, 2px borders on interactive elements, soft shadows on raised cards.",
      "## Do",
      "- Celebrate completion states (a short success message, a check mark).",
      "- Use friendly, plain-language labels.",
      "## Avoid",
      "- Dense tables and small tap targets.",
      "- Using the accent for body text.",
    ].join("\n"),
  },
  {
    id: "material",
    name: "Material-style",
    summary: "Tonal surfaces, pill-shaped buttons and a purple baseline in the spirit of Material 3.",
    tags: ["Android", "Consumer", "Productivity"],
    light: { bg: "#fef7ff", surface: "#ffffff", surface2: "#f3edf7", fg: "#1d1b20", fgMuted: "#49454f", border: "#e7e0ec", borderStrong: "#79747e", accent: "#6750a4", accentFg: "#ffffff", success: "#146c2e", warn: "#8c5000", danger: "#b3261e", info: "#0b57d0" },
    dark: { bg: "#141218", surface: "#1d1b20", surface2: "#2b2930", fg: "#e6e0e9", fgMuted: "#cac4d0", border: "#36343b", borderStrong: "#938f99", accent: "#d0bcff", accentFg: "#381e72", success: "#7dd88f", warn: "#ffb870", danger: "#f2b8b5", info: "#a8c7fa" },
    fonts: { display: ROBOTO, body: ROBOTO, mono: MONO },
    radius: 20,
    density: "comfortable",
    depth: "soft",
    border_width: 1,
    guidance: [
      "## Character",
      "Familiar, tactile and systematic, following Material 3 conventions (not an official Google theme).",
      "## Colour",
      "Tonal surfaces in the accent's hue; filled buttons for primary actions, tonal or outlined for the rest.",
      "## Shape and depth",
      "Fully rounded (pill) buttons and chips, 12–16px card corners, soft elevation on raised surfaces.",
      "## Do",
      "- Use a top app bar with the screen title and a floating action for the main create action on mobile.",
      "- Use chips for filters and segmented buttons for small choices.",
      "## Avoid",
      "- Square buttons and hard borders.",
      "- Google logos or product names.",
    ].join("\n"),
  },
  {
    id: "enterprise",
    name: "Enterprise",
    summary: "Dense, structured and sober. Navy accent, compact controls and data-first layouts.",
    tags: ["Admin", "B2B", "Data"],
    light: { bg: "#f4f6f8", surface: "#ffffff", surface2: "#eef1f4", fg: "#1b2330", fgMuted: "#4f5b6b", border: "#dce1e7", borderStrong: "#7d8896", accent: "#0b5cad", accentFg: "#ffffff", success: "#1e7d32", warn: "#a15c00", danger: "#b3261e", info: "#0b5cad" },
    dark: { bg: "#10151c", surface: "#171e27", surface2: "#1f2833", fg: "#e3e8ee", fgMuted: "#9aa6b4", border: "#2a3441", borderStrong: "#667385", accent: "#6aa9ff", accentFg: "#0b1320", success: "#6fd08c", warn: "#f6b454", danger: "#ff8a80", info: "#6aa9ff" },
    fonts: { display: HUMANIST, body: HUMANIST, mono: MONO },
    radius: 4,
    density: "compact",
    depth: "hairline",
    border_width: 1,
    guidance: [
      "## Character",
      "Serious, efficient and predictable. Built for people who use it all day.",
      "## Layout and density",
      "Compact controls, a left navigation, a page header with breadcrumbs and actions, then data.",
      "## Colour",
      "Navy for actions and selection only. Status colours carry meaning and always come with a label.",
      "## Do",
      "- Use tables with sortable headers, row actions and pagination for records.",
      "- Put filters above the table and bulk actions in a bar that appears on selection.",
      "## Avoid",
      "- Large hero areas and decorative imagery.",
      "- Hiding important actions in menus.",
    ].join("\n"),
  },
  {
    id: "mission-control",
    name: "Mission control",
    summary: "Dark-first, high-contrast panels with a teal signal colour. For monitoring and live data.",
    tags: ["Dashboard", "Monitoring", "Dark"],
    light: { bg: "#f2f5f7", surface: "#ffffff", surface2: "#e8eef2", fg: "#0f1a22", fgMuted: "#4b5b67", border: "#d5dee4", borderStrong: "#7a8a96", accent: "#0f766e", accentFg: "#ffffff", success: "#15803d", warn: "#a16207", danger: "#b91c1c", info: "#0369a1" },
    dark: { bg: "#0a0e12", surface: "#10161c", surface2: "#17202a", fg: "#e6edf3", fgMuted: "#8d9aa6", border: "#1f2a35", borderStrong: "#596876", accent: "#2dd4bf", accentFg: "#04201c", success: "#4ade80", warn: "#facc15", danger: "#f87171", info: "#38bdf8" },
    fonts: { display: MONO, body: SANS, mono: MONO },
    radius: 6,
    density: "compact",
    depth: "hairline",
    border_width: 1,
    guidance: [
      "## Character",
      "Focused and operational. Designed to be read at a glance and trusted under pressure.",
      "## Colour",
      "Dark by default. Teal marks the live or selected state; red, amber and green are reserved for health.",
      "## Typography",
      "Monospace for numbers, identifiers and headings; tabular figures so values line up.",
      "## Do",
      "- Use stat tiles with a label, a large value and a trend.",
      "- Show freshness (\"updated 12s ago\") on live data.",
      "## Avoid",
      "- Decorative charts without axes or units.",
      "- Colour as the only signal for status.",
    ].join("\n"),
  },
  {
    id: "warm-friendly",
    name: "Warm & friendly",
    summary: "Cream surfaces, a burnt-orange accent and soft rounding. Welcoming and human.",
    tags: ["Consumer", "Food", "Local business"],
    light: { bg: "#fffaf5", surface: "#ffffff", surface2: "#fdf0e3", fg: "#2a1d14", fgMuted: "#6a5646", border: "#f0e0cf", borderStrong: "#a08672", accent: "#c2410c", accentFg: "#ffffff", success: "#15803d", warn: "#a16207", danger: "#b91c1c", info: "#1d4ed8" },
    dark: { bg: "#1a130e", surface: "#231a13", surface2: "#2f231a", fg: "#fbeee2", fgMuted: "#c4ab95", border: "#3d2f24", borderStrong: "#86705e", accent: "#fb923c", accentFg: "#1a130e", success: "#4ade80", warn: "#facc15", danger: "#f87171", info: "#93c5fd" },
    fonts: { display: ROUNDED, body: HUMANIST, mono: MONO },
    radius: 12,
    density: "comfortable",
    depth: "soft",
    border_width: 1,
    guidance: [
      "## Character",
      "Friendly, generous and human — like a neighbourhood shop that knows your name.",
      "## Colour",
      "Cream and warm browns; the orange accent for the main action and highlights. Photography welcome.",
      "## Shape and depth",
      "Rounded cards with soft shadows; buttons slightly rounded, never pill-shaped.",
      "## Do",
      "- Write in a warm, direct voice (\"Your order is on its way\").",
      "- Use large, tappable cards for choices.",
      "## Avoid",
      "- Cold greys and blue accents.",
      "- Dense forms — split long forms into steps.",
    ].join("\n"),
  },
  {
    id: "elegant",
    name: "Elegant",
    summary: "Ivory, charcoal and antique gold with a refined serif. Quiet luxury and lots of air.",
    tags: ["Luxury", "Hospitality", "Fashion"],
    light: { bg: "#faf9f6", surface: "#ffffff", surface2: "#f2efe8", fg: "#1a1a1a", fgMuted: "#5a5650", border: "#e6e1d6", borderStrong: "#8f887b", accent: "#7a5c2e", accentFg: "#ffffff", success: "#2f6b3a", warn: "#8a5a00", danger: "#9f1d1d", info: "#2c4d7a" },
    dark: { bg: "#121110", surface: "#1a1917", surface2: "#24221f", fg: "#f2efe8", fgMuted: "#b2aa9c", border: "#34312c", borderStrong: "#7c7568", accent: "#d4b074", accentFg: "#121110", success: "#8fd19e", warn: "#e6c07a", danger: "#f19a9a", info: "#a9c3e8" },
    fonts: { display: SERIF_DISPLAY, body: SANS, mono: MONO },
    radius: 0,
    density: "spacious",
    depth: "flat",
    border_width: 1,
    guidance: [
      "## Character",
      "Restrained, confident and unhurried. Luxury is expressed through space and typography, not ornament.",
      "## Colour",
      "Ivory and charcoal; antique gold only for the primary action, links and fine rules.",
      "## Typography",
      "A refined serif for headlines with wide letter-spacing on small labels; a clean sans for body text.",
      "## Do",
      "- Use large images or calm empty space as the focal point.",
      "- Keep forms short, with plenty of space between fields.",
      "## Avoid",
      "- Badges, bright status colours and busy layouts.",
      "- Rounded corners.",
    ].join("\n"),
  },
  {
    id: "calm-nature",
    name: "Calm nature",
    summary: "Sage and forest greens with soft corners. Grounded, healthy and reassuring.",
    tags: ["Health", "Wellbeing", "Sustainability"],
    light: { bg: "#f6f8f4", surface: "#ffffff", surface2: "#ebf0e6", fg: "#18231c", fgMuted: "#4d5d52", border: "#dbe3d6", borderStrong: "#7f8f83", accent: "#2f6f4e", accentFg: "#ffffff", success: "#2f6f4e", warn: "#8a5a00", danger: "#a61b1b", info: "#285e8a" },
    dark: { bg: "#0f1512", surface: "#161e19", surface2: "#1f2a23", fg: "#e7efe8", fgMuted: "#9fb2a5", border: "#2a3830", borderStrong: "#63776a", accent: "#7fcf9f", accentFg: "#0f1512", success: "#7fcf9f", warn: "#e8c27a", danger: "#f19a9a", info: "#9cc7ea" },
    fonts: { display: HUMANIST, body: HUMANIST, mono: MONO },
    radius: 10,
    density: "comfortable",
    depth: "soft",
    border_width: 1,
    guidance: [
      "## Character",
      "Calm, trustworthy and gentle. Nothing shouts; progress feels steady.",
      "## Colour",
      "Sage surfaces and a forest-green accent. Warnings in amber, errors in a muted red.",
      "## Shape and depth",
      "Soft corners and light shadows; generous padding inside cards.",
      "## Do",
      "- Use progress indicators and gentle confirmations.",
      "- Prefer illustrations or nature photography over icons in empty states.",
      "## Avoid",
      "- Alarming colours for non-critical states.",
      "- Dense, data-heavy layouts.",
    ].join("\n"),
  },
  {
    id: "retro-paper",
    name: "Retro paper",
    summary: "Aged paper, brown ink, a rust accent and typewriter details. Crafted and nostalgic.",
    tags: ["Indie", "Craft", "Portfolio"],
    light: { bg: "#f3ecdc", surface: "#faf5e8", surface2: "#e9dfc8", fg: "#2b2118", fgMuted: "#5f5040", border: "#d8cbb0", borderStrong: "#8a7a62", accent: "#a4431f", accentFg: "#ffffff", success: "#3d6b2c", warn: "#8a5a00", danger: "#9f1d1d", info: "#2c4d7a" },
    dark: { bg: "#1b1611", surface: "#241d16", surface2: "#30271e", fg: "#efe5d0", fgMuted: "#bba98e", border: "#403428", borderStrong: "#85745d", accent: "#f08a5d", accentFg: "#1b1611", success: "#a3d18a", warn: "#e8c27a", danger: "#f19a9a", info: "#a9c3e8" },
    fonts: { display: MONO, body: SERIF_BODY, mono: MONO },
    radius: 4,
    density: "comfortable",
    depth: "hard",
    border_width: 2,
    guidance: [
      "## Character",
      "Handmade and nostalgic — a zine or a well-used notebook, not a costume.",
      "## Colour",
      "Paper and brown ink; rust for actions. Keep colour counts low, as if printed in two inks.",
      "## Typography",
      "Typewriter-style monospace for headings and labels, a bookish serif for reading text.",
      "## Do",
      "- Use 2px ink borders and a small offset shadow on cards.",
      "- Use stamps and tags (small bordered labels) for categories.",
      "## Avoid",
      "- Pure white and glossy effects.",
      "- Distressed textures that hurt readability.",
    ].join("\n"),
  },
  {
    id: "vibrant",
    name: "Vibrant",
    summary: "Clean white with a saturated magenta and bold geometric type. Energetic and modern.",
    tags: ["Marketing", "Events", "Creative"],
    light: { bg: "#ffffff", surface: "#ffffff", surface2: "#fbf0fd", fg: "#1a1025", fgMuted: "#5c5068", border: "#efe3f3", borderStrong: "#94859e", accent: "#a21caf", accentFg: "#ffffff", success: "#15803d", warn: "#b45309", danger: "#be123c", info: "#1d4ed8" },
    dark: { bg: "#120a17", surface: "#1b1222", surface2: "#281a31", fg: "#f7ecfb", fgMuted: "#b9a6c4", border: "#35243f", borderStrong: "#7d6a89", accent: "#f0abfc", accentFg: "#120a17", success: "#4ade80", warn: "#fbbf24", danger: "#fb7185", info: "#93c5fd" },
    fonts: { display: GEOMETRIC, body: SANS, mono: MONO },
    radius: 10,
    density: "comfortable",
    depth: "soft",
    border_width: 1,
    guidance: [
      "## Character",
      "Bold, upbeat and modern. Big type and one saturated colour carry the energy.",
      "## Colour",
      "White space with magenta for the primary action and key highlights; tinted panels for sections.",
      "## Typography",
      "A geometric display face at large sizes with tight tracking; plain sans for body text.",
      "## Do",
      "- Use oversized headlines and short, punchy copy.",
      "- Use the tinted fill to band sections of a page.",
      "## Avoid",
      "- More than one saturated colour.",
      "- Magenta text on tinted backgrounds.",
    ].join("\n"),
  },
  {
    id: "terminal",
    name: "Developer terminal",
    summary: "Monospace everywhere, a phosphor-green accent and tight spacing. Built for developers.",
    tags: ["Developer tools", "CLI", "Dark"],
    light: { bg: "#fafafa", surface: "#ffffff", surface2: "#f0f2f0", fg: "#111811", fgMuted: "#4c574c", border: "#dde3dd", borderStrong: "#7d887d", accent: "#047857", accentFg: "#ffffff", success: "#047857", warn: "#a16207", danger: "#b91c1c", info: "#1d4ed8" },
    dark: { bg: "#0d1117", surface: "#131a22", surface2: "#1b232d", fg: "#e6edf3", fgMuted: "#8b98a5", border: "#232d38", borderStrong: "#5e6b79", accent: "#3fb950", accentFg: "#07120a", success: "#3fb950", warn: "#d29922", danger: "#f85149", info: "#58a6ff" },
    fonts: { display: MONO, body: MONO, mono: MONO },
    radius: 4,
    density: "compact",
    depth: "hairline",
    border_width: 1,
    guidance: [
      "## Character",
      "Technical, fast and honest. Feels like a good terminal: dense, legible and keyboard-first.",
      "## Colour",
      "Dark by default; green marks success and the primary action, blue marks links.",
      "## Typography",
      "Monospace for everything. Use weight and colour, not size, for hierarchy.",
      "## Do",
      "- Show keyboard shortcuts next to actions.",
      "- Use code blocks with a copy button for commands.",
      "## Avoid",
      "- Rounded, bubbly shapes and illustrations.",
      "- Proportional fonts for data.",
    ].join("\n"),
  },
];

export function findPreset(id: string): DesignSystemPreset | undefined {
  return DESIGN_SYSTEM_PRESETS.find((p) => p.id === id);
}
